FIRMWARE_VERSION=miva-lpddr3-260922-0945
IMAGE_FILE=miva-lpddr3-260922-0945.img.xz
VERIFY_SHA256=yes

INSTALLER_IP=192.168.10.48
INSTALLER_PREFIX=24
INSTALLER_GATEWAY=192.168.10.1
INSTALLER_DNS=192.168.10.1,1.1.1.1
INSTALLER_PASSWORD=change-me-installer

DEVICE_IP=192.168.1.102
DEVICE_PREFIX=24
DEVICE_GATEWAY=192.168.1.1
DEVICE_DNS=192.168.1.1,1.1.1.1
DEVICE_PASSWORD=admin123@
DEVICE_HOSTNAME=miva

MIVA_TAG=v3.0.5p8
LED_GPIO=262
SHUTDOWN_AFTER=yes
